Refactor : 장바구니 조회 코드 수정
Prompt-oven/cart-service pull request #16
Opened 2024-11-19 06:39 UTC by JaeHunLee-git

- GetMapping 시 RequestBody를 쓸 수 없기에 PathVariable 사용 코드로 수정

2024-11-19 09:02 UTC, yuseok-kim-edushare approved these changes

2024-11-19 10:26 UTC, lazarus0320 requested changes

2024-11-19 10:26 UTC, lazarus0320 commented on src/main/java/com/promptoven/cartservice/adapter/in/web/mapper/CartVoMapper.java
> +    public CartRequestDto toDeleteDto(CartDeleteRequestVo cartDeleteRequestVo) {
이거 memberUuid랑 productUuid가 엔티티에서 가져오는 값인가요? 카트 제거에 memberUuid와 productUuid가 필요한지 잘모르겠습니다. cartUuid만 있어도 될거라고 생각해서 그렇습니다.

2024-11-20 01:36 UTC, JaeHunLee-git commented on src/main/java/com/promptoven/cartservice/adapter/in/web/mapper/CartVoMapper.java
> +    public CartRequestDto toDeleteDto(CartDeleteRequestVo cartDeleteRequestVo) {
cartId로 수정 완료

2024-11-20 01:39 UTC, merged